### ISSUE TITLE
Task list for V4 release

### ISSUE THREAD

**Issue by marwan** [marwan/quranwbw#33]
Following is the task list/todo for the next major release. No new features are planned apart from the ones already added. Main priority will be to implement features from the current live website.

- [ ] work on verses range repeat
- [ ] #57
- [ ] update credits and add new ones
- [ ] enable service worker
- [x] update the Tajweed font end icons color for other themes and add black version
- [x] #58
- [x] add meta data to pages, robot.txt, PWA, favicon
- [x] add bottom nav/audio bar
- [x] implement a feature to auto-import bookmarks from the existing site to this new version
- [x] update all division points (https://github.com/marwan/quranwbw-svelte/issues/25)
- [x] add all the available WBW languages in meta
- [x] add relevant fonts for translations (Urdu, Bangla, etc...)
- [x] implement Tailwind CSS via NPM rather than CDN
- [x] migrate from Flowbite to Flowbite-Svelte

**Comment by marwan** [comment]
Credits to be added for word morphology description.
